#!/bin/bash

IFS=$'\n'
dir=$1
RESULT=`ls -a $dir | sort`
declare -a ARRAY
declare -a FIRSTARRAY
let count=0
let firstcount=0

for FILE in $RESULT
do
    if [ ! -L "$dir/$FILE" ] && [ ! -d "$dir/$FILE" ]
	then
	if [ ! -r "$dir/$FILE" ]
	    then
	    echo "You have no read permission for the file $dir/$FILE."
	elif [ -f "$dir/$FILE" ]
	    then
	    if [[ "$(basename "$FILE")" == .* ]]
		then
		FIRSTARRAY[$firstcount]="$dir/$FILE"
		let firstcount=$firstcount+1
	    else
		ARRAY[$count]="$dir/$FILE"
		let count=$count+1
	    fi
	fi
    fi
done

#Combine ARRAY and FIRSTARRAY
ARRAY=("${FIRSTARRAY[@]}" "${ARRAY[@]}")
let count=count+firstcount
echo $count

for (( i=0;i<$count;i++ ))
do
    for (( j=$i+1;j<$count;j++ ))
    do
	file1="ls -i ${ARRAY[i]}"
	file2="ls -i ${ARRAY[j]}"
	compare=`cmp -s $file1 $file2`
	if [ ! compare ]
	    then
	    ln -f "${ARRAY[$i]}" "${ARRAY[$j]}"
	fi
    done
done






